export {default as Button} from './button/button';
export {default as ButtonFix} from './button/button-fix';
export {default as Input} from './input';
export {default as TextArea} from './textarea';
export {default as Checkbox} from './checkbox';
export {default as RadioGroup} from './radio-group';
export {default as Radio} from './radio';
export {default as Inform} from './inform';
export {default as Popup} from './popup';